-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the existing tables - this section generated from drop.tpl
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_text_select_config`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_text_select_config
-- *
-- *******************************************************/
CREATE TABLE `civicrm_text_select_config` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique TextSelectConfig ID',
  `option_group_id` int unsigned COMMENT 'FK to Option Group',
  `field_id` varchar(255) COMMENT 'custom field ID',
  PRIMARY KEY (`id`),
  CONSTRAINT FK_civicrm_text_select_config_id FOREIGN KEY (`id`) REFERENCES `civicrm_option_group`(`id`) ON DELETE CASCADE
)
ENGINE=InnoDB;
